# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZvZCaWRoYPjC53yfl7RGccNu-8macsg
"""

pip install tensorflow

pip install opencv-python

pip install cvlib

pip install matplotlib

import cv2

import cvlib as cv 
from cvlib.object_detection import draw_bbox

import matplotlib.pyplot as plt

image = cv2.imread('/content/sample_data/pep.jpg')

box,label,c_score= cv.detect_common_objects(image)

output = draw_bbox(image,box,label,c_score)

plt.imshow(output)

plt.show()

print(label)

count = 0
for i in label:
    if(i == "person"):
        print("Person Exist !")
        count= count + 1
print('Result of People Counting is :', count)